### PR TITLE
Fixed some of the issues brought up in the last pull request.

### PR DESCRIPTION
**Pull request by thomashare**

### CODE REVIEW

**Comment by sjosegarcia** [comment]
Since this hasn't been merged, would it be possible to show the default fiat price along with the zil price inside the wallet.

**Comment by hicaru** [comment]
This PR with incorrect rect styles.

**Comment by thomashare** [comment]
> This PR with incorrect rect styles.

What exactly do you mean by this?

**Comment by hicaru** [comment]
if you want see the styles issue, run command `yarn serve` or `npm run serve`

**Comment by thomashare** [comment]
I didn't receive any errors when running that command on my end. Also, I fixed some pretty major CSS flaws in the code that was causing visual distortions in the app.

**Comment by hicaru** [comment]
ok, i will check it

**Comment by hicaru** [comment]
image
incorect started page.

**Comment by hicaru** [comment]
incorect image

**Comment by hicaru** [comment]
cannot click back or and accept 
image

**Comment by hicaru** [comment]
incorect size popup mode

**Comment by hicaru** [comment]
incorect size for accounts popup mode 
image

**Comment by hicaru** [comment]
cannot see node list 
image

**Pull request closed without merging**
